version: '3.8'

services:
  backend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose backend on port 3000
    volumes:
      - ./admin:/usr/src/app
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Expose frontend on port 3001
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NODE_ENV: development
      API_URL: http://localhost:3000  
    command: npm run dev -- -p 3001  
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    container_name: flux-ecommerce-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  redis:
    image: redis:latest
    container_name: flux-ecommerce-redis
    ports:
      - "6379:6379"
